### ISSUE TITLE
作为脚手架是不是多余的东西太多了？

### ISSUE THREAD

**Issue by JakeWoki** [easy-team/easywebpack-cli#12]
按现在单页面这样可以当做一个demo了，要删去很多东西的。还有page目录下的一些命名等和vue推荐的目录结构有差别，感觉很不好。另外如果用[nuxt](https://github.com/nuxt/nuxt.js)渲染要怎么搞？小白求助

**Comment by hubcarl** [comment]
目录根据自己喜好调整，没有强制约束
