### ISSUE TITLE
less 模板初始化Demo同步修改

### ISSUE THREAD

**Issue by IveChen** [easy-team/easywebpack-cli#13]
bug描述：
![image](https://user-images.githubusercontent.com/1736282/51010119-dcc54a80-158d-11e9-9d25-e440bfa8ce33.png)
选择的是less，但是出来的模板用的是scss...
工程为vue client render application -> vue single page application
easywebpack版本号:4.3.2

**Comment by hubcarl** [comment]
目前这里只是初始化 webpack配置和依赖，具体less 需要自己修改，后面考虑完善一下
