### ISSUE TITLE
easy build prod 运行失败不报错

### ISSUE THREAD

**Issue by z1o** [easy-team/easywebpack-cli#14]
当
![image](https://user-images.githubusercontent.com/39619397/51521468-a88d3c00-1e61-11e9-9762-a8cf527dc9dd.png)
manifest.json root 其他文件为user 使用user账号运行easy build prod肯定不能覆盖manifest.json
但是不会报错
![image](https://user-images.githubusercontent.com/39619397/51521629-205b6680-1e62-11e9-863c-01dab69e89db.png)
只能通过以下方法定位
![image](https://user-images.githubusercontent.com/39619397/51521681-441eac80-1e62-11e9-8386-6154b4d516b9.png)

**Comment by hubcarl** [comment]
这个是你系统权限问题，请调整权限设置
