### ISSUE TITLE
easywebpack init 到选择第二步就停止了，项目目录文件也都不存在，也不报错直接退出了

### ISSUE THREAD

**Issue by RuthlessPotato** [easy-team/easywebpack-cli#16]

**Comment by hubcarl** [comment]
@RuthlessPotato  系统和 node 版本是多少？ 如果是 windows 10 ，用 linux bash shell 试试

**Comment by hangge666** [comment]
我也是，运行完init就这样一直没反应了
![image](https://user-images.githubusercontent.com/32354383/56455269-dca7c880-638e-11e9-9471-f1818498fa04.png)

**Comment by fallenaAngel** [comment]
![image](https://user-images.githubusercontent.com/39083913/62118448-47529380-b2f0-11e9-8170-b29855e6237c.png)
tong'shagn同上

**Comment by fengcaian** [comment]
也遇到这个问题了，在win7 64位出现的，dos和cmder里面都是停在了第二步，git bash里面能往下走，但是上下键不能选择，只能用数字选择，选择后里面的排版都乱了，得仔细找选项。

**Comment by hubcarl** [comment]
如果是 windows 10 ，请用 linux bash shell  @fengcaian

**Comment by fengcaian** [comment]
win7 64位，node是v10.13.0，用easywebpack init构建了一个项目可以，然后删除了这个项目，构建第二个的时候就不行了，随后使用git bash可以发现可以构建，只是选择可选项的时候页面信息很乱，最后用git bash构建成功了。

**Comment by hubcarl** [comment]
目前 Inquirer 在 windows 上面有一些问题，具体看一下这个 https://github.com/SBoudrias/Inquirer.js/issues?utf8=%E2%9C%93&q=windows

windows 10 建议用一下 linux bash shell
