### ISSUE TITLE
The easy init command is not available

### ISSUE THREAD

**Issue by SunnyCyx** [easy-team/easywebpack-cli#19]
I use the` easy init` command to create Egg + Vue Application，but don't work.its stuck.
![image](https://user-images.githubusercontent.com/50090089/64576839-ed43f400-d3ac-11e9-8cbb-a42e87c9d665.png)
the version of easywebpack-cli is 4.60

**Comment by hubcarl** [comment]
@SunnyCyx windows 用 windows 10 linux bash shell

**Comment by SunnyCyx** [comment]
> @SunnyCyx windows用windows 10 linux bash shell

谢谢 用linux的命令行就能解决
