### ISSUE TITLE
cnpm run build uglifyJs bug

### ISSUE THREAD

**Issue by ifuner** [easy-team/easywebpack-cli#23]
问题描述 / 复现
1.  git clone https://github.com/easy-team/egg-vue-webpack-boilerplate.git
2. 修改webpack.config.js (修改如下)
plugins: [
        {imagemini: false},
        process.env.NODE_ENV !== "development"
            ? {
                uglifyJs: {
                    args: {
                        uglifyOptions: {
                            warnings: false,
                            compress: {
                                dead_code: true,
                                drop_console: true,
                                drop_debugger: true
                            },
                            output: {
                                comments: false
                            }
                        }
                    }
                }
            }
            : {}
    ]

![image](https://user-images.githubusercontent.com/25742540/82122153-70cba580-97c4-11ea-871f-12a4b49630a5.png)

3. cnpm run build (抛错)

Unexpected token: keyword «const»

思考：网上找到相关的问题解释是uglifyJs 不支持es6的语法，所以才会出现这个问题

**Comment by hubcarl** [comment]
@ifuner  webpack 4 无需配置这个了，通过内置的默认配置即可 https://www.yuque.com/easy-team/easywebpack/optimizaiton

**Comment by hubcarl** [comment]
https://www.yuque.com/easy-team/easywebpack/problem#7ZEnA
