### ISSUE TITLE
运行easywebpack dll报错

### ISSUE THREAD

**Issue by Imprevia** [easy-team/easywebpack-cli#26]
https://github.com/easy-team/easywebpack-cli/blob/7181b27aa88bfa4ab30b19edb8f211f5ab19cdfe/lib/action.js#L78

program参数少了this.
const config = utils.initWebpackConfig(this.program, { env, framework: 'dll' }, { dll: true });

**Comment by hubcarl** [comment]
@Imprevia  
- + easywebpack-cli@4.8.1
