### ISSUE TITLE
不能正常运行

### ISSUE THREAD

**Issue by DoveAz** [easy-team/easywebpack-cli#6]
win10 1709  node 10.4.0
运行   easy init 之后  随便选一个然后就会卡住
![image](https://user-images.githubusercontent.com/15158280/42010235-4d559908-7ac0-11e8-99d6-3e2b17038bef.png)

**Comment by hubcarl** [comment]
node 10 目前还没有进行测试，请使用 Node 8.X  LTS 版本

**Comment by hubcarl** [comment]
@DoveAz  这个是window默认  cmd 支持问题，请用 windows 10 的 linux shell 或者 PowerShell
